version: '3.8'

services:
  config-service:
    build:
      context: ./config-service
    ports:
      - 8888:8888
    networks:
      - my-net
    profile-service:
      build:
        context: ./profile-service
      ports:
        - 8081:8081
      environment:
        - SPRING_CLOUD_CONFIG_URI=http://192.168.1.9:8888/
      depends_on:
        - config-service
      networks:
        - my-net
networks:
  my-net:
    driver: bridge